import Head from 'next/head';
import Table from '../components/Table';


export default function Home() {
  return (
    <>
      <Head>
        <title>Shtrafov Net Test | Клиенты</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="shortcut icon" href="#"></link>
      </Head>
      <main>
        <div className='container mt-5'>
					<div className='row mb-3'>
						<div className='col d-flex justify-content-between'>
							<h4>Клиенты</h4>
							<button className='btn btn-primary'>+ Добавить клиента</button>
						</div>
					</div>
          <Table />
        </div>
      </main>
    </>
  );
}
